import { MigrationInterface, QueryRunner } from "typeorm";

export class AddStatusColumn1766912751661 implements MigrationInterface {
    name = 'AddStatusColumn1766912751661'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`users\` (\`user_id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(100) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`full_name\` varchar(100) NULL, \`avatar_url\` varchar(255) NULL, \`role\` enum ('STUDENT', 'ADMIN') NOT NULL DEFAULT 'STUDENT', \`status\` enum ('ACTIVE', 'BLOCKED') NOT NULL DEFAULT 'ACTIVE', \`total_score\` int NOT NULL DEFAULT '0', \`solved_problems\` int NOT NULL DEFAULT '0', \`current_streak\` int NOT NULL DEFAULT '0', \`max_streak\` int NOT NULL DEFAULT '0', \`last_active\` datetime NULL, \`reset_otp\` varchar(10) NULL, \`reset_otp_expires\` datetime NULL, \`is_verified\` tinyint NOT NULL DEFAULT 0, \`verification_otp\` varchar(10) NULL, \`verification_otp_expires\` datetime NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), PRIMARY KEY (\`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`test_cases\` (\`test_case_id\` int NOT NULL AUTO_INCREMENT, \`problem_id\` int NOT NULL, \`input_data\` longtext NOT NULL, \`expected_output\` longtext NOT NULL, \`is_sample\` tinyint NOT NULL COMMENT 'Is this a sample test case shown to user' DEFAULT 0, \`is_hidden\` tinyint NOT NULL COMMENT 'Is this test case hidden from user' DEFAULT 1, \`explanation\` text NULL COMMENT 'Explanation for sample test cases', \`score\` int NOT NULL COMMENT 'Score for this test case' DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`test_case_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`categories\` (\`category_id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(100) NOT NULL, \`icon_url\` varchar(255) NULL, \`order_index\` int NOT NULL DEFAULT '0', \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`category_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`languages\` (\`language_id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(50) NOT NULL, \`code\` varchar(20) NOT NULL, \`version\` varchar(20) NULL, \`docker_image\` varchar(100) NOT NULL, \`compile_command\` varchar(500) NULL, \`run_command\` varchar(500) NOT NULL, \`file_extension\` varchar(10) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_7397752718d1c9eb873722ec9b\` (\`code\`), PRIMARY KEY (\`language_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`try_it_yourself\` (\`try_it_yourself_id\` int NOT NULL AUTO_INCREMENT, \`lesson_id\` int NOT NULL, \`language_id\` int NOT NULL, \`example_code\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_5dcce06778e247578c40d3e88d\` (\`lesson_id\`), UNIQUE INDEX \`REL_5dcce06778e247578c40d3e88d\` (\`lesson_id\`), PRIMARY KEY (\`try_it_yourself_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`lessons\` (\`lesson_id\` int NOT NULL AUTO_INCREMENT, \`category_id\` int NOT NULL, \`title\` varchar(200) NOT NULL, \`description\` text NULL, \`content\` longtext NOT NULL, \`difficulty_level\` enum ('BEGINNER', 'INTERMEDIATE', 'ADVANCED') NOT NULL DEFAULT 'BEGINNER', \`order_index\` int NOT NULL DEFAULT '0', \`is_published\` tinyint NOT NULL DEFAULT 0, \`view_count\` int NOT NULL DEFAULT '0', \`created_by\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`lesson_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`votes\` (\`vote_id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`discussion_id\` int NULL, \`reply_id\` int NULL, \`vote_type\` enum ('UPVOTE', 'DOWNVOTE') NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_dfec6c750a53f65d11c95653d2\` (\`user_id\`, \`discussion_id\`, \`reply_id\`), PRIMARY KEY (\`vote_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`discussion_replies\` (\`reply_id\` int NOT NULL AUTO_INCREMENT, \`discussion_id\` int NOT NULL, \`user_id\` int NOT NULL, \`content\` longtext NOT NULL, \`upvotes\` int NOT NULL DEFAULT '0', \`downvotes\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`reply_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`discussions\` (\`discussion_id\` int NOT NULL AUTO_INCREMENT, \`problem_id\` int NULL, \`lesson_id\` int NULL, \`user_id\` int NOT NULL, \`title\` varchar(200) NOT NULL, \`content\` longtext NOT NULL, \`discussion_type\` enum ('QUESTION', 'SOLUTION', 'GENERAL', 'BUG_REPORT') NOT NULL DEFAULT 'QUESTION', \`is_solution\` tinyint NOT NULL DEFAULT 0, \`upvotes\` int NOT NULL DEFAULT '0', \`downvotes\` int NOT NULL DEFAULT '0', \`view_count\` int NOT NULL DEFAULT '0', \`reply_count\` int NOT NULL DEFAULT '0', \`is_pinned\` tinyint NOT NULL DEFAULT 0, \`is_locked\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`discussion_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problems\` (\`problem_id\` int NOT NULL AUTO_INCREMENT, \`title\` varchar(200) NOT NULL, \`description\` longtext NOT NULL, \`difficulty\` enum ('EASY', 'MEDIUM', 'HARD') NOT NULL DEFAULT 'EASY', \`time_limit\` int NOT NULL COMMENT 'Time limit in milliseconds' DEFAULT '1000', \`memory_limit\` int NOT NULL COMMENT 'Memory limit in MB' DEFAULT '256', \`points\` int NOT NULL DEFAULT '100', \`acceptance_rate\` decimal(5,2) NOT NULL DEFAULT '0.00', \`total_submissions\` int NOT NULL DEFAULT '0', \`accepted_submissions\` int NOT NULL DEFAULT '0', \`created_by\` int NOT NULL, \`is_published\` tinyint NOT NULL DEFAULT 0, \`is_daily_challenge\` tinyint NOT NULL COMMENT 'Auto-managed by daily challenge scheduler' DEFAULT 0, \`input_format\` text NULL COMMENT 'Description of input format', \`output_format\` text NULL COMMENT 'Description of output format', \`constraints\` text NULL COMMENT 'Problem constraints', \`samples\` json NULL COMMENT 'Sample inputs/outputs', \`author_notes\` text NULL COMMENT 'Private notes from author', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`problem_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`tags\` (\`tag_id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(50) NOT NULL, \`slug\` varchar(100) NOT NULL, \`description\` varchar(255) NULL, \`color\` varchar(7) NULL COMMENT 'Hex color code', \`icon\` varchar(50) NULL COMMENT 'Icon class or name', \`order_index\` int NOT NULL COMMENT 'Display order' DEFAULT '0', \`is_active\` tinyint NOT NULL DEFAULT 1, \`problem_count\` int NOT NULL COMMENT 'Number of problems with this tag' DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_d90243459a697eadb8ad56e909\` (\`name\`), UNIQUE INDEX \`IDX_b3aa10c29ea4e61a830362bd25\` (\`slug\`), PRIMARY KEY (\`tag_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`submissions\` (\`submission_id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`problem_id\` int NOT NULL, \`language_id\` int NOT NULL, \`source_code\` longtext NOT NULL, \`status\` enum ('PENDING', 'RUNNING', 'ACCEPTED', 'WRONG_ANSWER', 'TIME_LIMIT', 'MEMORY_LIMIT', 'RUNTIME_ERROR', 'COMPILE_ERROR', 'INTERNAL_ERROR') NOT NULL DEFAULT 'PENDING', \`execution_time\` int NULL COMMENT 'Execution time in milliseconds', \`memory_used\` int NULL COMMENT 'Memory used in KB', \`points_earned\` int NOT NULL DEFAULT '0', \`test_cases_passed\` int NOT NULL DEFAULT '0', \`total_test_cases\` int NOT NULL DEFAULT '0', \`error_message\` text NULL, \`language\` varchar(50) NULL COMMENT 'Language name', \`language_version\` varchar(50) NULL COMMENT 'Language version', \`stdout\` longtext NULL COMMENT 'Standard output', \`stderr\` longtext NULL COMMENT 'Standard error', \`execution_logs\` json NULL COMMENT 'Detailed execution logs', \`submitted_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`submission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_recommendations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`type\` enum ('PROBLEM', 'LESSON') NOT NULL DEFAULT 'PROBLEM', \`item_id\` int NOT NULL, \`reason\` text NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ai_messages\` (\`id\` int NOT NULL AUTO_INCREMENT, \`conversation_id\` int NOT NULL, \`role\` enum ('user', 'assistant') NOT NULL, \`message\` text NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ai_conversations\` (\`id\` int NOT NULL AUTO_INCREMENT, \`problem_id\` int NOT NULL, \`user_id\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`lesson_exercises\` (\`exercise_id\` int NOT NULL AUTO_INCREMENT, \`lesson_id\` int NOT NULL, \`question\` varchar(200) NOT NULL, \`exercise_type\` enum ('MULTIPLE_CHOICE', 'TRUE_FALSE') NOT NULL DEFAULT 'MULTIPLE_CHOICE', \`options\` json NOT NULL, \`correct_answer\` varchar(10) NOT NULL, \`explanation\` text NULL, \`order_index\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`exercise_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`exercise_submissions\` (\`submission_id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`exercise_id\` int NOT NULL, \`lesson_id\` int NOT NULL, \`user_answer\` varchar(10) NOT NULL, \`correct_answer\` varchar(10) NOT NULL, \`is_correct\` tinyint NOT NULL, \`time_spent_seconds\` int NULL, \`attempt_number\` int NOT NULL DEFAULT '1', \`submitted_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`submission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`daily_activities\` (\`activity_id\` int NOT NULL AUTO_INCREMENT, \`user_id\` int NOT NULL, \`activity_date\` date NOT NULL, \`problems_solved\` int NOT NULL DEFAULT '0', \`lessons_completed\` int NOT NULL DEFAULT '0', \`time_spent\` int NOT NULL DEFAULT '0', \`points_earned\` int NOT NULL DEFAULT '0', \`streak_day\` int NOT NULL DEFAULT '0', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`activity_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`problem_tags\` (\`problem_id\` int NOT NULL, \`tag_id\` int NOT NULL, INDEX \`IDX_e369a453fb95b878301184cadd\` (\`problem_id\`), INDEX \`IDX_853473f54d7b1e91b236346fa1\` (\`tag_id\`), PRIMARY KEY (\`problem_id\`, \`tag_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`test_cases\` ADD CONSTRAINT \`FK_b64ac4d24cd9a87eda34b2a9457\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`problem_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`try_it_yourself\` ADD CONSTRAINT \`FK_5dcce06778e247578c40d3e88d9\` FOREIGN KEY (\`lesson_id\`) REFERENCES \`lessons\`(\`lesson_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`try_it_yourself\` ADD CONSTRAINT \`FK_4256540837367c7aa706218cfbc\` FOREIGN KEY (\`language_id\`) REFERENCES \`languages\`(\`language_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`lessons\` ADD CONSTRAINT \`FK_3428c38507b4f9edf3a921d1b2a\` FOREIGN KEY (\`category_id\`) REFERENCES \`categories\`(\`category_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`lessons\` ADD CONSTRAINT \`FK_b96adc7c3e06624edae3e0a01ae\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`votes\` ADD CONSTRAINT \`FK_27be2cab62274f6876ad6a31641\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`votes\` ADD CONSTRAINT \`FK_23477a8c9fb0f75a70ab348beb4\` FOREIGN KEY (\`discussion_id\`) REFERENCES \`discussions\`(\`discussion_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`votes\` ADD CONSTRAINT \`FK_bf3b2d17a8c0c9926697e03374c\` FOREIGN KEY (\`reply_id\`) REFERENCES \`discussion_replies\`(\`reply_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discussion_replies\` ADD CONSTRAINT \`FK_e3ea46ba52dba54bcec7394aa55\` FOREIGN KEY (\`discussion_id\`) REFERENCES \`discussions\`(\`discussion_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discussion_replies\` ADD CONSTRAINT \`FK_a7c1e71e05f39b37cfd2168dcf9\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discussions\` ADD CONSTRAINT \`FK_cab096931ed863699d402d30faf\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`problem_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discussions\` ADD CONSTRAINT \`FK_79212043b84fa5438c38ce14380\` FOREIGN KEY (\`lesson_id\`) REFERENCES \`lessons\`(\`lesson_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`discussions\` ADD CONSTRAINT \`FK_6bae1005971de66491e2f46037b\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problems\` ADD CONSTRAINT \`FK_2aee58a468d036cc139963ae789\` FOREIGN KEY (\`created_by\`) REFERENCES \`users\`(\`user_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submissions\` ADD CONSTRAINT \`FK_fca12c4ddd646dea4572c6815a9\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`submissions\` ADD CONSTRAINT \`FK_d7613a2172f2115adb054c4c16e\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`problem_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` ADD CONSTRAINT \`FK_b65c00f26f1cceff8a096abdf6f\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ai_messages\` ADD CONSTRAINT \`FK_de21fcb2d1df7fd6ca70f555b6d\` FOREIGN KEY (\`conversation_id\`) REFERENCES \`ai_conversations\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ai_conversations\` ADD CONSTRAINT \`FK_46af2fa83595081896d15e3e2d3\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`problem_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ai_conversations\` ADD CONSTRAINT \`FK_12fdbf99ca0da93085d61edd3bb\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`lesson_exercises\` ADD CONSTRAINT \`FK_e10837d987befdf2a6b5a4f337b\` FOREIGN KEY (\`lesson_id\`) REFERENCES \`lessons\`(\`lesson_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exercise_submissions\` ADD CONSTRAINT \`FK_c39ce7d682f2a9541103ab90bbd\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`exercise_submissions\` ADD CONSTRAINT \`FK_27d8633f56e0de84c6ca1f80e10\` FOREIGN KEY (\`exercise_id\`) REFERENCES \`lesson_exercises\`(\`exercise_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`daily_activities\` ADD CONSTRAINT \`FK_41b2afd0f87258187d2b2fc171e\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`problem_tags\` ADD CONSTRAINT \`FK_e369a453fb95b878301184caddc\` FOREIGN KEY (\`problem_id\`) REFERENCES \`problems\`(\`problem_id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`problem_tags\` ADD CONSTRAINT \`FK_853473f54d7b1e91b236346fa13\` FOREIGN KEY (\`tag_id\`) REFERENCES \`tags\`(\`tag_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`problem_tags\` DROP FOREIGN KEY \`FK_853473f54d7b1e91b236346fa13\``);
        await queryRunner.query(`ALTER TABLE \`problem_tags\` DROP FOREIGN KEY \`FK_e369a453fb95b878301184caddc\``);
        await queryRunner.query(`ALTER TABLE \`daily_activities\` DROP FOREIGN KEY \`FK_41b2afd0f87258187d2b2fc171e\``);
        await queryRunner.query(`ALTER TABLE \`exercise_submissions\` DROP FOREIGN KEY \`FK_27d8633f56e0de84c6ca1f80e10\``);
        await queryRunner.query(`ALTER TABLE \`exercise_submissions\` DROP FOREIGN KEY \`FK_c39ce7d682f2a9541103ab90bbd\``);
        await queryRunner.query(`ALTER TABLE \`lesson_exercises\` DROP FOREIGN KEY \`FK_e10837d987befdf2a6b5a4f337b\``);
        await queryRunner.query(`ALTER TABLE \`ai_conversations\` DROP FOREIGN KEY \`FK_12fdbf99ca0da93085d61edd3bb\``);
        await queryRunner.query(`ALTER TABLE \`ai_conversations\` DROP FOREIGN KEY \`FK_46af2fa83595081896d15e3e2d3\``);
        await queryRunner.query(`ALTER TABLE \`ai_messages\` DROP FOREIGN KEY \`FK_de21fcb2d1df7fd6ca70f555b6d\``);
        await queryRunner.query(`ALTER TABLE \`user_recommendations\` DROP FOREIGN KEY \`FK_b65c00f26f1cceff8a096abdf6f\``);
        await queryRunner.query(`ALTER TABLE \`submissions\` DROP FOREIGN KEY \`FK_d7613a2172f2115adb054c4c16e\``);
        await queryRunner.query(`ALTER TABLE \`submissions\` DROP FOREIGN KEY \`FK_fca12c4ddd646dea4572c6815a9\``);
        await queryRunner.query(`ALTER TABLE \`problems\` DROP FOREIGN KEY \`FK_2aee58a468d036cc139963ae789\``);
        await queryRunner.query(`ALTER TABLE \`discussions\` DROP FOREIGN KEY \`FK_6bae1005971de66491e2f46037b\``);
        await queryRunner.query(`ALTER TABLE \`discussions\` DROP FOREIGN KEY \`FK_79212043b84fa5438c38ce14380\``);
        await queryRunner.query(`ALTER TABLE \`discussions\` DROP FOREIGN KEY \`FK_cab096931ed863699d402d30faf\``);
        await queryRunner.query(`ALTER TABLE \`discussion_replies\` DROP FOREIGN KEY \`FK_a7c1e71e05f39b37cfd2168dcf9\``);
        await queryRunner.query(`ALTER TABLE \`discussion_replies\` DROP FOREIGN KEY \`FK_e3ea46ba52dba54bcec7394aa55\``);
        await queryRunner.query(`ALTER TABLE \`votes\` DROP FOREIGN KEY \`FK_bf3b2d17a8c0c9926697e03374c\``);
        await queryRunner.query(`ALTER TABLE \`votes\` DROP FOREIGN KEY \`FK_23477a8c9fb0f75a70ab348beb4\``);
        await queryRunner.query(`ALTER TABLE \`votes\` DROP FOREIGN KEY \`FK_27be2cab62274f6876ad6a31641\``);
        await queryRunner.query(`ALTER TABLE \`lessons\` DROP FOREIGN KEY \`FK_b96adc7c3e06624edae3e0a01ae\``);
        await queryRunner.query(`ALTER TABLE \`lessons\` DROP FOREIGN KEY \`FK_3428c38507b4f9edf3a921d1b2a\``);
        await queryRunner.query(`ALTER TABLE \`try_it_yourself\` DROP FOREIGN KEY \`FK_4256540837367c7aa706218cfbc\``);
        await queryRunner.query(`ALTER TABLE \`try_it_yourself\` DROP FOREIGN KEY \`FK_5dcce06778e247578c40d3e88d9\``);
        await queryRunner.query(`ALTER TABLE \`test_cases\` DROP FOREIGN KEY \`FK_b64ac4d24cd9a87eda34b2a9457\``);
        await queryRunner.query(`DROP INDEX \`IDX_853473f54d7b1e91b236346fa1\` ON \`problem_tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_e369a453fb95b878301184cadd\` ON \`problem_tags\``);
        await queryRunner.query(`DROP TABLE \`problem_tags\``);
        await queryRunner.query(`DROP TABLE \`daily_activities\``);
        await queryRunner.query(`DROP TABLE \`exercise_submissions\``);
        await queryRunner.query(`DROP TABLE \`lesson_exercises\``);
        await queryRunner.query(`DROP TABLE \`ai_conversations\``);
        await queryRunner.query(`DROP TABLE \`ai_messages\``);
        await queryRunner.query(`DROP TABLE \`user_recommendations\``);
        await queryRunner.query(`DROP TABLE \`submissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_b3aa10c29ea4e61a830362bd25\` ON \`tags\``);
        await queryRunner.query(`DROP INDEX \`IDX_d90243459a697eadb8ad56e909\` ON \`tags\``);
        await queryRunner.query(`DROP TABLE \`tags\``);
        await queryRunner.query(`DROP TABLE \`problems\``);
        await queryRunner.query(`DROP TABLE \`discussions\``);
        await queryRunner.query(`DROP TABLE \`discussion_replies\``);
        await queryRunner.query(`DROP INDEX \`IDX_dfec6c750a53f65d11c95653d2\` ON \`votes\``);
        await queryRunner.query(`DROP TABLE \`votes\``);
        await queryRunner.query(`DROP TABLE \`lessons\``);
        await queryRunner.query(`DROP INDEX \`REL_5dcce06778e247578c40d3e88d\` ON \`try_it_yourself\``);
        await queryRunner.query(`DROP INDEX \`IDX_5dcce06778e247578c40d3e88d\` ON \`try_it_yourself\``);
        await queryRunner.query(`DROP TABLE \`try_it_yourself\``);
        await queryRunner.query(`DROP INDEX \`IDX_7397752718d1c9eb873722ec9b\` ON \`languages\``);
        await queryRunner.query(`DROP TABLE \`languages\``);
        await queryRunner.query(`DROP TABLE \`categories\``);
        await queryRunner.query(`DROP TABLE \`test_cases\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
    }

}
